apiVersion: apps/v1
kind: Deployment
metadata:
  name: pupweb1
  namespace: flux-testagain
spec:
  selector:
    matchLabels:
      app: pupweb1
  replicas: 2
  template:
    metadata:
      labels:
        app: pupweb1
    spec:
      containers:
      - name: pupweb1
        image: nginx
        ports:
        - containerPort: 80
---
  
apiVersion: v1
kind: Service
metadata:
  namespace: flux-testagain
  name: pupweb1
  labels:
    app: pupweb1
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: pupweb1
