apiVersion: apps/v1
kind: Deployment
metadata:
  name: pupweb
spec:
  selector:
    matchLabels:
      app: pupweb
  replicas: 4
  template:
    metadata:
      labels:
        app: pupweb
    spec:
      containers:
      - name: pupweb
        image: nginx
        ports:
        - containerPort: 80
---
  
apiVersion: v1
kind: Service
metadata:
  name: pupweb
  labels:
    app: pupweb
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 80
  selector:
    app: pupweb
